@startuml
autonumber
actor user
user -> front : выбор мероприятия
front -> back : запрос доступных мест и цен
back -> back : проверить доступные места и цену
back -> front : свободные места и цены
user -> front : выбор мест и нажать кнопку для брони
front -> back : запрос на бронирование мест
back -> back : проверить доступность мест и временно заблокировать
alt #Lightgreen Места доступны для бронировния
back -> front : подтверждение брони
front -> user : заполнить данные для оплаты
user -> front : ввод данных (реквизиты, фио, тел, почта)
front -> paymentsys : передача зашифрованной платежной информации
paymentsys -> user : запрос кода для подверждения списания
user -> paymentsys : ввод кода
alt #LightGreen Успешный платеж
paymentsys -> paymentsys : списание средств
paymentsys -> back : подтверждение платежа
back -> back : внести информацию о бронировании в БД
back -> front : информация о бронировании
front -> user : сгенерированный билет на экран и почту
else #lightpink Ошибка платежа
paymentsys -> back : Код ошибки
back -> front : Текст ошибки и дальнейшие действия
end
else #lightpink Билеты недоступны для бронирования
back -> front : билеты не доступны для бронирования
front -> user : выберите другие места
@enduml
