@startuml
title Рекламная кампания (РК)
[*] --> СоздатьМакет
СоздатьМакет --> ОпубликоватьРК
ОпубликоватьРК --> СоздатьОффер : найти блогера
state СоздатьОффер {
[*] -->  Оффер
Оффер --> Согласовать : блогер принимает оффер
Оффер --> НайтиСледующего : блогер отклоняет оффер
НайтиСледующего --> Оффер
Согласовать --> СоздатьСделку : селлер согласовал
Согласовать --> НайтиСледующего : селлер не согласовал
}
state СоздатьСделку {
[*] --> Сделка
Сделка --> ПодтвержденоВыполнение : выполнена
Сделка --> Спор : не выполнена
ПодтвержденоВыполнение --> ПереводОплаты
ПодтвержденоВыполнение --> ОплатыНет
ОплатыНет --> Спор
Спор --> РешениеСпора
ПереводОплаты --> ПолучениеОплаты
}
РешениеСпора --> [*]
ПолучениеОплаты --> [*]
@enduml
