@startuml
title Рекламная сделка
state Черновик
state Модерация
state Активация
state Оффер
state В_работе
state НаПроверке
state Спор
state Завершено
state Отмена
[*] --> Черновик : создать кампанию
Черновик --> Модерация : заполнить ТЗ, бюджет, креативы
Модерация --> Черновик : [Guard: бюджет <5000р или нет креативов] Отправить сообщение селлеру
Модерация --> Активация : [модератор одобрил]
state Активация {
  state Поиск
  state ЗаморозкаБюджета
  [*] --> ЗаморозкаБюджета
  ЗаморозкаБюджета --> Поиск
  Поиск --> Оффер
}
state Оффер {
  state ОжиданиеОтклика
  [*] -->  ОжиданиеОтклика : оффер
  ОжиданиеОтклика --> В_работе : блогер принимает оффер
  ОжиданиеОтклика --> Отклонен : блогер отклоняет оффер
  ОжиданиеОтклика --> Просрочен
  Просрочен --> [*]
  В_работе --> БлогерЗабанен
  БлогерЗабанен --> Отмена
  В_работе --> СредстваНеЗаморожены
  СредстваНеЗаморожены --> Отмена
  В_работе --> НаПроверке
  НаПроверке --> Завершено : блогер загрузил пост
  

}
Завершено --> [*]  : перевод оплаты и комиссии
@enduml
