@startuml
title Диаграмма состояний Рекламная сделка

state Черновик
state Модерация
state АктивацияРК


[*] --> Черновик : создать кампанию, заполнить ТЗ, бюджет, креативы
Черновик --> Модерация : нажать "Запустить РК"\n РК улетает на модерацию
Модерация --> Черновик : [Guard: бюджет <5000р или нет креативов]\nКомментарий: "Добавить денег/креативы"
Модерация --> АктивацияРК : модератор одобрил

state АктивацияРК {
  state Поиск
  state ЗаморозкаБюджета
  state Оффер
  state Завершено
  state Отмена
  [*] --> ЗаморозкаБюджета
  ЗаморозкаБюджета --> Поиск
  Поиск --> Оффер

  state Оффер {
    state ОжиданиеОтклика
    state В_работе
    state НаПроверке
    state Спор
    [*] -->  ОжиданиеОтклика : система рассылает офферы (до 10 блогерам)
    ОжиданиеОтклика --> В_работе : блогер нажал "Принять" блоге не забанен или средства заморожены
    ОжиданиеОтклика --> Отмена : блогер нажал "Отклонить"
    ОжиданиеОтклика --> Отмена : блогер не отвечает на оффер в течение 24 часов
    В_работе --> Отмена : блогер забанен / средства не заморожены
    В_работе --> НаПроверке : блогер загрузил пост/reels
    НаПроверке --> В_работе : селлер отклонил на доработку
    НаПроверке --> Завершено : селлер нажал "Одобрить"
    В_работе --> Спор : блогер не загрузил пост
    
}
}
Завершено --> [*]  : перевод оплаты и комиссии
Отмена --> [*]
@enduml
